### ISSUE TITLE
挂了啊

### ISSUE THREAD

**Issue by zhjnerv** [CyberWaifu-org/CharacterEditor#6]
网站进入，`爱丽丝正在维护服务器老师也请稍等一会` 从平安夜到现在，已经过去12小时了。
问题是从 https://status.cyberwaifu.org/status/cyberwaifu 确定所有服务都是正常。到底是我的网络问题呢。还是网站的真的挂了？

**Comment by CyberWaifu-org** [comment]
Fixed it~
